---
title: "UV8 Autofluorescence Hotspot"
format: html
---

```{r}
StorageLocation <- file.path("Figures", "Figure_CosineHotspotSignatures")
```

Load required packages via library call 

```{r}
library(flowCore)
library(flowWorkspace)
library(CytoML)
library(Luciernaga)
library(dplyr)
library(purrr)
library(stringr)
library(ggplot2)
```

List path to unstained .fcs files

```{r}
Location <- file.path("/home", "david", "Desktop", "AutofluorescentHotspot")
Unstained <- list.files(Location, pattern=".fcs", full.names=TRUE)

StringRemoval <- c("(Cells)" , " ", ".fcs")

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1), normalize=FALSE)

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("DegradingAPCFire810RawSignatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)

Signatures <- Luciernaga_FolderSignatures(
    FolderPath=Location, sample.name="GUID",
    StringRemoval=StringRemoval, fluorophore.name="",
    Verbose=TRUE, PanelCuts=c(0.5,1))

LinePlot <- QC_ViewSignature(x=NULL, data=Signatures, Normalize = FALSE, columnname="Sample", legend=FALSE)
 
FileName <- paste0("DegradingAPCFire810Signatures", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, LinePlot, dpi = 600, width = 4, height = 3)
````

```{r}
CosineData <- Signatures |> select(-Fluorophore)
CosinePlot <- Luciernaga::Luciernaga_Cosine(data=CosineData, limitlow=0.9, legend=TRUE)

FileName <- paste0("UV8vsV7similarity", ".png")
FinalLocation <- file.path(StorageLocation, FileName)
ggsave(filename = FinalLocation, CosinePlot, dpi = 600, width = 4, height = 3)
```

```{r}
MyPanel <- c("BUV395", "BUV563", "BUV615", "BUV661", "BUV737", "BUV805", "Spark Violet 423", "Pacific Blue", "BV480","BV570", "BV605", "BV650", "BV711", "BV750", "BV786",
"Alexa Fluor 488", "Spark Blue 550", "Spark Blue 574", "RB613", "RB705", "RB780",
"PE", "PE-Dazzle 594", "PE-Cy5", "PE-Fire 700", "PE-Fire 744", "PE-Vio 770", "PE-Fire 810", "APC", "Alexa Fluor 647", "Zombie NIR", "APC-R700", "APC-Fire 750", "APC-Fire 810")

Checking <- CosineData |> select(-Sample)

HotspotBasePlot <- Luciernaga:::MagesCauldron(panelfluors=MyPanel, unstained=Checking, returnType="plot")

Brightest <- APCFire810_90to100 |> select(-Sample)
Dimmest <- APCFire810_10to20 |> select(-Sample)

#QC_ReferenceLibrary(FluorNameContains="APC-Fire 810", NumberDetectors = 64)

HotspotBrightest <- Luciernaga:::MagesCauldron(panelfluors=MyPanel,
     unstained=Checking, swapname="AFTags",
     swapvalue=Brightest, returnType="plot", outpath=StorageLocation,
     savePlot=TRUE, filename="BrightHotspot")

HotspotDimmest <- Luciernaga:::MagesCauldron(panelfluors=MyPanel,
     unstained=UnstainedSignatureInput, swapname="AFTags",
     swapvalue=Dimmest, returnType="data", savePlot=TRUE, 
     outpath=StorageLocation, filename="DimHotspot")

Difference <- Luciernaga:::TailOfANewt(HotspotBrighter=HotspotBrightest,
 HotspotDimmer=HotspotDimmest, savePlot=TRUE,
 savePlot=TRUE, filename="HotspotDifference",
 outpath=StorageLocation)

 HotspotBrightest <- Luciernaga:::MagesCauldron(panelfluors=MyPanel,
     unstained=UnstainedSignatureInput, swapname="APC-Fire 810",
     swapvalue=Brightest, returnType="plot", outpath=StorageLocation,
     savePlot=TRUE, filename="BrightHotspot")

HotspotDimmest <- Luciernaga:::MagesCauldron(panelfluors=MyPanel,
     unstained=UnstainedSignatureInput, swapname="APC-Fire 810",
     swapvalue=Dimmest, returnType="plot", savePlot=TRUE, 
     outpath=StorageLocation, filename="DimHotspot")
```